### ISSUE TITLE
Please add a license file and a screen shot

### ISSUE THREAD

**Issue by unixorn** [ThemysciraData/owczarczak.zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by KellieOwczarczak** [comment]
Still been tweaking the theme, so I really had not taken any screen shot until today. 

Not sure about licenses. Do people do that for themes? 🤨

**Comment by unixorn** [comment]
Having a license makes it easier for people to use it and potentially contribute. I generally go Apache 2.0 or BSD for my own stuff.

**Comment by KellieOwczarczak** [comment]
Ok. It seemed that others used MIT, so I went with that after looking.
